// <auto-generated />
using System;
using CopyCat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CopyCat.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CopyCatDbContext))]
    partial class CopyCatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CopyCat.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.ChannelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveFilterSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveRewriteSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("BackfillCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForwardingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LiveForwardingEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveFilterSetId");

                    b.HasIndex("ActiveRewriteSetId");

                    b.HasIndex("TargetChannelId");

                    b.HasIndex("SourceChannelId", "TargetChannelId")
                        .IsUnique();

                    b.ToTable("ChannelMappings");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.ChannelSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastBackfilledMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<long?>("LastSeenMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ChannelId")
                        .IsUnique();

                    b.ToTable("ChannelSyncStates");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.FilterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FilterSets");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.FilterVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FilterDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FilterSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilterSetId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("FilterVersions");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.ForwardingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FilterVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ForwardingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RewriteVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TargetTelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "MappingId")
                        .IsUnique();

                    b.HasIndex("Status", "NextRetryAt");

                    b.ToTable("ForwardingJobs");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileUniqueId")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramFileId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.MessageDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FilterVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchedRuleId")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewritePreview")
                        .HasColumnType("text");

                    b.Property<Guid?>("RewriteVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "MappingId")
                        .IsUnique();

                    b.ToTable("MessageDecisions");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.MessageLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayText")
                        .HasColumnType("text");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageLinks");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.RewriteSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RewriteSets");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.RewriteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RewriteSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RewriteSetId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RewriteVersions");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.StoredMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupedId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedText")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceChannelId")
                        .HasColumnType("uuid");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceChannelId", "TelegramMessageId")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.TelegramChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessHash")
                        .HasColumnType("text");

                    b.Property<bool?>("CanAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanCreateRelatedTargets")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanPost")
                        .HasColumnType("boolean");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSource")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("boolean");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("TelegramChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TelegramChannelId")
                        .IsUnique();

                    b.ToTable("TelegramChannels");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.TelegramControlOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid?>("MappingId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("TelegramControlOperations");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.TelegramSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiHashEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("ApiIdEncrypted")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PendingChallenge")
                        .HasColumnType("text");

                    b.Property<string>("PendingPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberMasked")
                        .HasColumnType("text");

                    b.Property<string>("SessionDataEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TelegramSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.ChannelMapping", b =>
                {
                    b.HasOne("CopyCat.Domain.Entities.FilterSet", "ActiveFilterSet")
                        .WithMany()
                        .HasForeignKey("ActiveFilterSetId");

                    b.HasOne("CopyCat.Domain.Entities.RewriteSet", "ActiveRewriteSet")
                        .WithMany()
                        .HasForeignKey("ActiveRewriteSetId");

                    b.HasOne("CopyCat.Domain.Entities.TelegramChannel", "SourceChannel")
                        .WithMany()
                        .HasForeignKey("SourceChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyCat.Domain.Entities.TelegramChannel", "TargetChannel")
                        .WithMany()
                        .HasForeignKey("TargetChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActiveFilterSet");

                    b.Navigation("ActiveRewriteSet");

                    b.Navigation("SourceChannel");

                    b.Navigation("TargetChannel");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.FilterVersion", b =>
                {
                    b.HasOne("CopyCat.Domain.Entities.FilterSet", "FilterSet")
                        .WithMany("Versions")
                        .HasForeignKey("FilterSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterSet");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.MessageAttachment", b =>
                {
                    b.HasOne("CopyCat.Domain.Entities.StoredMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.MessageLink", b =>
                {
                    b.HasOne("CopyCat.Domain.Entities.StoredMessage", "Message")
                        .WithMany("Links")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.RewriteVersion", b =>
                {
                    b.HasOne("CopyCat.Domain.Entities.RewriteSet", "RewriteSet")
                        .WithMany("Versions")
                        .HasForeignKey("RewriteSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewriteSet");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.TelegramChannel", b =>
                {
                    b.HasOne("CopyCat.Domain.Entities.TelegramSession", "Session")
                        .WithMany("Channels")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.FilterSet", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.RewriteSet", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.StoredMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("CopyCat.Domain.Entities.TelegramSession", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
